language: node_js
dist: bionic
sudo: required

branches:
  only:
    - master
    - /^greenkeeper/.*$/

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

install:
  - npm install cloudfront-invalidate-cli -g
  - yarn

before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 3

script:
  - yarn run export
  - yarn run test:ci

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: eu-central-1
  local_dir: out
  skip_cleanup: true

after_deploy:
  - cf-invalidate -- $CLOUDFRONT_ID index.html
