language: node_js

branches:
  only:
    - master

install:
  - npm install cloudfront-invalidate-cli -g
  - npm install

script:
- npm run export

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: eu-central-1
  local_dir: out
  skip_cleanup: true

after_deploy:
  - cf-invalidate -- $CLOUDFRONT_ID index.html
