language: node_js
dist: trusty
sudo: required

branches:
  only:
    - master
    - /^greenkeeper/.*$/

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

install:
  - npm install cloudfront-invalidate-cli -g
  - yarn

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
- yarn run export
- yarn run test:ci

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: eu-central-1
  local_dir: out
  skip_cleanup: true

after_deploy:
  - cf-invalidate -- $CLOUDFRONT_ID index.html
