language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install cloudfront-invalidate-cli -g
  - yarn

script:
- yarn run export
# - yarn run test:ci

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: eu-central-1
  local_dir: out
  skip_cleanup: true

after_deploy:
  - cf-invalidate -- $CLOUDFRONT_ID index.html
